/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.dao;

import java.sql.SQLException;

import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import fr.formation.youtube.bean.Audio;
import fr.formation.youtube.dao.commons.DAOProvider;
import fr.formation.youtube.dao.commons.DAOTestUtil;

/**
 * JUnit tests for AudioDAO
 * 
 * @author Telosys Tools
 *
 */
public class AudioDAOTest {


	private static final String CREATE_TABLE = 
			 "CREATE TABLE audio ("
			+ "ID_AUDIO,"
			+ "NOM_AUDIO VARCHAR(45) ,"
			+ "PRIMARY KEY(ID_AUDIO)"
			+ ");"
			;

	@BeforeClass
	public static void init() {
		DAOTestUtil.initDatabase(CREATE_TABLE) ;
	}

	@Test
	public void testDAO() throws SQLException {
    	System.out.println("test AudioDAO ");
    	AudioDAO dao = DAOProvider.getDAO(AudioDAO.class);

    	Assert.assertTrue( dao.count() == 0 );

    	Audio audio = new Audio();
		//--- Key values
		// Auto-incremented key : nothing to set in the Primary Key
		//--- Other values
		audio.setNomAudio("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"); // "NOM_AUDIO" : java.lang.String

    	//--- INSERT
    	System.out.println("Insert : " + audio );
    	Integer pkAutoIncr = dao.insert(audio);
    	audio.setIdAudio( pkAutoIncr );
    	Assert.assertTrue( dao.exists(pkAutoIncr) );
    	Assert.assertTrue( dao.count() == 1 );
    	Assert.assertTrue( dao.exists(audio) );
    	
    	//--- FIND
    	System.out.println("Find..." );
    	Audio audio2 = dao.find(pkAutoIncr);
    	Assert.assertNotNull(audio2);
    	Assert.assertTrue( dao.exists(audio2) ) ;
    	
    	
    	
    	
  
    	
    	System.out.println("Normal end of DAO test." );
	}

}
