/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.dao;

import java.sql.SQLException;

import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import fr.formation.youtube.bean.PlaylistHasVideo;
import fr.formation.youtube.dao.commons.DAOProvider;
import fr.formation.youtube.dao.commons.DAOTestUtil;

/**
 * JUnit tests for PlaylistHasVideoDAO
 * 
 * @author Telosys Tools
 *
 */
public class PlaylistHasVideoDAOTest {


	private static final String CREATE_TABLE = 
			 "CREATE TABLE playlist_has_video ("
			+ "FK_ID_PLAYLIST INTEGER NOT NULL,"
			+ "FK_ID_VIDEO INTEGER NOT NULL,"
			+ "PRIMARY KEY(FK_ID_PLAYLIST,FK_ID_VIDEO)"
			+ ");"
			;

	@BeforeClass
	public static void init() {
		DAOTestUtil.initDatabase(CREATE_TABLE) ;
	}

	@Test
	public void testDAO() throws SQLException {
    	System.out.println("test PlaylistHasVideoDAO ");
    	PlaylistHasVideoDAO dao = DAOProvider.getDAO(PlaylistHasVideoDAO.class);

    	Assert.assertTrue( dao.count() == 0 );

    	PlaylistHasVideo playlistHasVideo = new PlaylistHasVideo();
		//--- Key values
		playlistHasVideo.setFkIdPlaylist(100); // "FK_ID_PLAYLIST" : java.lang.Integer
		playlistHasVideo.setFkIdVideo(100); // "FK_ID_VIDEO" : java.lang.Integer
		//--- Other values

    	//--- INSERT
    	System.out.println("Insert : " + playlistHasVideo );
    	dao.insert(playlistHasVideo);
    	Assert.assertTrue( dao.exists(100, 100) );
    	Assert.assertTrue( dao.count() == 1 );
    	Assert.assertTrue( dao.exists(playlistHasVideo) );
    	
    	//--- FIND
    	System.out.println("Find..." );
    	PlaylistHasVideo playlistHasVideo2 = dao.find(100, 100);
    	Assert.assertNotNull(playlistHasVideo2);
		Assert.assertTrue( playlistHasVideo2.getFkIdPlaylist() == 100  ) ;
		Assert.assertTrue( playlistHasVideo2.getFkIdVideo() == 100  ) ;
    	Assert.assertTrue( dao.exists(playlistHasVideo2) ) ;
    	
    	//--- NO UPDATE FOR THIS ENTITY (ALL COLUMNS IN PRIMARY KEY)
    	
    	//--- LOAD
    	PlaylistHasVideo playlistHasVideo3 = new PlaylistHasVideo();
    	playlistHasVideo3.setFkIdPlaylist(100);
    	playlistHasVideo3.setFkIdVideo(100);
    	Assert.assertTrue( dao.load(playlistHasVideo3) );
    	System.out.println("Loaded : " + playlistHasVideo3 );


    	playlistHasVideo3.setFkIdPlaylist(300);
    	playlistHasVideo3.setFkIdVideo(300);
    	Assert.assertFalse( dao.load(playlistHasVideo3) );
    	
    	//--- DELETE
    	System.out.println("Delete : " + playlistHasVideo2 );
    	Assert.assertTrue( dao.delete(playlistHasVideo2) == 1 );
    	Assert.assertTrue( dao.delete(playlistHasVideo2) == 0 );
    	Assert.assertTrue( dao.delete(100, 100) == 0 );

    	Assert.assertTrue( dao.count() == 0 );
    	Assert.assertFalse( dao.exists(100, 100) ) ;
    	Assert.assertFalse( dao.exists(playlistHasVideo2) ) ;
    	playlistHasVideo2 = dao.find(100, 100);
    	Assert.assertNull( playlistHasVideo2 );
    	
    	System.out.println("Normal end of DAO test." );
	}

}
