/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.dao;

import fr.formation.youtube.bean.Audio;

/**
 * Audio DAO interface
 * 
 * @author Telosys Tools
 */
public interface AudioDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idAudio
	 * @return the bean found or null if not found 
	 */
	public Audio find( Integer idAudio ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param audio
	 * @return true if found, false if not found
	 */
	public boolean load( Audio audio ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param audio
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(Audio audio) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param audio
	 * @return
	 */
	public int update(Audio audio) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param idAudio
	 * @return
	 */
	public int delete( Integer idAudio ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param audio
	 * @return
	 */
	public int delete( Audio audio ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param idAudio
	 * @return
	 */
	public boolean exists( Integer idAudio ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param audio
	 * @return
	 */
	public boolean exists( Audio audio ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
