/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.dao;

import fr.formation.youtube.bean.Playlist;

/**
 * Playlist DAO interface
 * 
 * @author Telosys Tools
 */
public interface PlaylistDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idPlaylist
	 * @return the bean found or null if not found 
	 */
	public Playlist find( Integer idPlaylist ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param playlist
	 * @return true if found, false if not found
	 */
	public boolean load( Playlist playlist ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param playlist
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(Playlist playlist) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param playlist
	 * @return
	 */
	public int update(Playlist playlist) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param idPlaylist
	 * @return
	 */
	public int delete( Integer idPlaylist ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param playlist
	 * @return
	 */
	public int delete( Playlist playlist ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param idPlaylist
	 * @return
	 */
	public boolean exists( Integer idPlaylist ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param playlist
	 * @return
	 */
	public boolean exists( Playlist playlist ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
