/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.dao;

import fr.formation.youtube.bean.PlaylistHasAudio;

/**
 * PlaylistHasAudio DAO interface
 * 
 * @author Telosys Tools
 */
public interface PlaylistHasAudioDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param fkIdPlaylist
	 * @param fkIdAudio
	 * @return the bean found or null if not found 
	 */
	public PlaylistHasAudio find( Integer fkIdPlaylist, Integer fkIdAudio ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param playlistHasAudio
	 * @return true if found, false if not found
	 */
	public boolean load( PlaylistHasAudio playlistHasAudio ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param playlistHasAudio
	 */
	public void insert(PlaylistHasAudio playlistHasAudio) ;


    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param fkIdPlaylist
	 * @param fkIdAudio
	 * @return
	 */
	public int delete( Integer fkIdPlaylist, Integer fkIdAudio ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param playlistHasAudio
	 * @return
	 */
	public int delete( PlaylistHasAudio playlistHasAudio ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param fkIdPlaylist
	 * @param fkIdAudio
	 * @return
	 */
	public boolean exists( Integer fkIdPlaylist, Integer fkIdAudio ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param playlistHasAudio
	 * @return
	 */
	public boolean exists( PlaylistHasAudio playlistHasAudio ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
