/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.formation.annuaire;

import fr.formation.annuaire.dao.ArrondissementDAO;
import fr.formation.annuaire.dao.ContacteDAO;
import fr.formation.annuaire.pojo.Arrondissement;
import fr.formation.annuaire.pojo.Contacte;
import fr.formation.annuaire.utils.ConnectionBDD;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

/**
 *
 * @author formation
 */
public class AnnuaireForm extends javax.swing.JFrame {

    private Connection connection;

    /**
     * Creates new form AnnuaireForm
     */
    public AnnuaireForm() {
        initComponents();
        // initialisation
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxArrondissement = new javax.swing.JComboBox();
        arrondissementDeParis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneContact = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboBoxArrondissement.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxArrondissementItemStateChanged(evt);
            }
        });
        comboBoxArrondissement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxArrondissementActionPerformed(evt);
            }
        });

        arrondissementDeParis.setText("Arrondissement de Paris");

        jScrollPane1.setViewportView(textPaneContact);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(arrondissementDeParis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(comboBoxArrondissement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arrondissementDeParis)
                    .addComponent(comboBoxArrondissement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxArrondissementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxArrondissementActionPerformed

        String nomArrondissementSelected = comboBoxArrondissement.getSelectedItem().toString();

        ArrondissementDAO arrondissementDAO = new ArrondissementDAO(this.connection);

        int idArrondissementSelected = arrondissementDAO.getIdFromNomArrondissement(nomArrondissementSelected);

        ContacteDAO contacteDAO = new ContacteDAO(this.connection);

        List<Contacte> listeContacteSelected = contacteDAO.findByArrondissement(idArrondissementSelected);

        String affichage = "";
        for (Contacte contacteSelected : listeContacteSelected) {
            affichage+= contacteSelected.toString();
        }
        
        textPaneContact.setText(affichage);
        
        
    }//GEN-LAST:event_comboBoxArrondissementActionPerformed

    private void comboBoxArrondissementItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxArrondissementItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxArrondissementItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnnuaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnnuaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnnuaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnnuaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnnuaireForm annuaire = new AnnuaireForm();
                annuaire.setVisible(true);
                annuaire.setTitle("Annuaire de paris");
            }

        });

    }

    /**
     * Initialisation
     */
    private void init() {
        // TODO add your handling code here:
        ConnectionBDD connectionBDD = new ConnectionBDD();

        // mapping de la connexion de l'annuaire "this.connection"  avec la connexion retournée par 
        // connectionBDD.openConnectionBDD()
        this.connection = connectionBDD.openConnectionBDD();

        // Création (instantiation) d'un DAO de l'arrondissement en utilisant le
        // constructeur de la classe ArrondissementDAO qui prend en paramètre 
        // la connexion de l'annuaire "this.connection" 
        ArrondissementDAO arrondissementDAO = new ArrondissementDAO(this.connection);

        // récupération de la liste des arrondissement mappée avec la liste "listeArrondissement" 
        // en executant la requête "select_all" définie dans la méthode findAllArrondissement() du DAO
        List<Arrondissement> listeArrondissement = arrondissementDAO.findAllArrondissement();

        comboBoxArrondissement.addItem("");

        // boucle sur la liste des arrondissements et ajout d'un item dans la combo box de
        // l'arrondissement courant
        for (Arrondissement arrond : listeArrondissement) {
            comboBoxArrondissement.addItem(arrond.getNomArrondissement());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrondissementDeParis;
    private javax.swing.JComboBox comboBoxArrondissement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textPaneContact;
    // End of variables declaration//GEN-END:variables

}
