/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.bean;

import java.io.Serializable;


/**
 * Java bean for 'Audio' entity
 * 
 * @author Telosys Tools
 *
 */
public class Audio implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : ID_AUDIO INT UNSIGNED 
    private Integer idAudio;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : NOM_AUDIO VARCHAR 
    private String nomAudio;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdAudio( Integer idAudio ) {
        this.idAudio = idAudio ;
    }

    public Integer getIdAudio() {
        return this.idAudio;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNomAudio( String nomAudio ) {
        this.nomAudio = nomAudio;
    }
    public String getNomAudio() {
        return this.nomAudio;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idAudio);
        sb.append("|");
        sb.append(nomAudio);
        return sb.toString(); 
    } 


}