/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.bean;

import java.io.Serializable;


/**
 * Java bean for 'Playlist' entity
 * 
 * @author Telosys Tools
 *
 */
public class Playlist implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : ID_PLAYLIST INT UNSIGNED 
    private Integer idPlaylist;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : FK_ID_UTILISATEUR INT UNSIGNED 
    private Integer fkIdUtilisateur;

    // DB : NOM_PLAYLIST VARCHAR 
    private String nomPlaylist;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdPlaylist( Integer idPlaylist ) {
        this.idPlaylist = idPlaylist ;
    }

    public Integer getIdPlaylist() {
        return this.idPlaylist;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setFkIdUtilisateur( Integer fkIdUtilisateur ) {
        this.fkIdUtilisateur = fkIdUtilisateur;
    }
    public Integer getFkIdUtilisateur() {
        return this.fkIdUtilisateur;
    }

    public void setNomPlaylist( String nomPlaylist ) {
        this.nomPlaylist = nomPlaylist;
    }
    public String getNomPlaylist() {
        return this.nomPlaylist;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idPlaylist);
        sb.append("|");
        sb.append(fkIdUtilisateur);
        sb.append("|");
        sb.append(nomPlaylist);
        return sb.toString(); 
    } 


}
