/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.bean;

import java.io.Serializable;


/**
 * Java bean for 'PlaylistHasVideo' entity
 * 
 * @author Telosys Tools
 *
 */
public class PlaylistHasVideo implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : FK_ID_PLAYLIST INT UNSIGNED 
    private Integer fkIdPlaylist;
    // DB : FK_ID_VIDEO INT UNSIGNED 
    private Integer fkIdVideo;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFkIdPlaylist( Integer fkIdPlaylist ) {
        this.fkIdPlaylist = fkIdPlaylist ;
    }

    public Integer getFkIdPlaylist() {
        return this.fkIdPlaylist;
    }

    public void setFkIdVideo( Integer fkIdVideo ) {
        this.fkIdVideo = fkIdVideo ;
    }

    public Integer getFkIdVideo() {
        return this.fkIdVideo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(fkIdPlaylist);
        sb.append("|");
        sb.append(fkIdVideo);
        return sb.toString(); 
    } 


}
