/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.bean;

import java.io.Serializable;


/**
 * Java bean for 'Video' entity
 * 
 * @author Telosys Tools
 *
 */
public class Video implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : ID_VIDEO INT UNSIGNED 
    private Integer idVideo;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : NOM_VIDEO VARCHAR 
    private String nomVideo;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdVideo( Integer idVideo ) {
        this.idVideo = idVideo ;
    }

    public Integer getIdVideo() {
        return this.idVideo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNomVideo( String nomVideo ) {
        this.nomVideo = nomVideo;
    }
    public String getNomVideo() {
        return this.nomVideo;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idVideo);
        sb.append("|");
        sb.append(nomVideo);
        return sb.toString(); 
    } 


}
