/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.dao.commons;

import javax.sql.DataSource;

import fr.formation.youtube.dao.impl.spring.commons.SpringConfiguration;
import org.springframework.context.ApplicationContext;
//import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

/**
 * DAO instance provider
 * 
 * @author Telosys Tools
 * 
 */
public class DAOProvider {

	// private final static ApplicationContext applicationContext = new
	// ClassPathXmlApplicationContext("spring-context.xml");
	// CREATION DU CONTEXTE SPRING AVEC LES DEFINITIONS CONTENUES DANS LA
	// CONFIGURATION SPRING : SpringConfiguration.class
	private final static ApplicationContext applicationContext = new AnnotationConfigApplicationContext(
			SpringConfiguration.class);

	public final static <T> T getDAO(Class<T> clazz) {
		return applicationContext.getBean(clazz);
	}

	public final static DataSource getDataSource() {
		DataSourceHolder dataSourceHolder = applicationContext
				.getBean(DataSourceHolder.class);
		return dataSourceHolder.getDatasource();
	}

}
