/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.dao.commons;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * DataSource holder
 * 
 * @author Telosys Tools
 *
 */
// Un repository = 1 component
@Repository("dataSourceHolder")
public class DataSourceHolder {
	
	// injection du bean (component) id = datasource de classe javax.sql.DataSource
	@Autowired
	private DataSource datasource ;
	
	public DataSource getDatasource() {
		return datasource;
	}

}
