/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.dao.impl.spring;

import java.sql.ResultSet;
import java.sql.SQLException;

import fr.formation.youtube.bean.Audio;
import fr.formation.youtube.dao.AudioDAO;
import fr.formation.youtube.dao.impl.spring.commons.GenericDAO;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

/**
 * Audio DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
@Repository
public class AudioDAOImplSpring extends GenericDAO<Audio> implements AudioDAO {

	private final static String SQL_SELECT = 
		"select ID_AUDIO, NOM_AUDIO from audio where ID_AUDIO = ?";

	// NB : This entity has an auto-incremented primary key : "ID_AUDIO"
	private final static String AUTO_INCREMENTED_COLUMN = "ID_AUDIO";

	private final static int[] SQL_INSERT_TYPES = new int[] {
			java.sql.Types.VARCHAR   // "NOM_AUDIO" : VARCHAR(45) - java.lang.String
	};

	private final static String SQL_INSERT = 
		"insert into audio ( NOM_AUDIO ) values ( ? )";

	private final static String SQL_UPDATE = 
		"update audio set NOM_AUDIO = ? where ID_AUDIO = ?";

	private final static String SQL_DELETE = 
		"delete from audio where ID_AUDIO = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from audio";

	private final static String SQL_COUNT = 
		"select count(*) from audio where ID_AUDIO = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public AudioDAOImplSpring() {
		super(AUTO_INCREMENTED_COLUMN, SQL_INSERT_TYPES);
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public Audio find( Integer idAudio ) {
		Object[] primaryKey = new Object[] { idAudio };
		return super.doSelect(primaryKey);		
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public boolean load( Audio audio ) {
		return super.doSelect(audio) ;
	}
	
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public Integer insert(Audio audio) {
		Long key = super.doInsertAutoIncr(audio);
		return key.intValue();
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public int update(Audio audio) {
		return super.doUpdate(audio);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public int delete( Integer idAudio ) {
		Object[] primaryKey = new Object[] { idAudio };
		return super.doDelete(primaryKey);		
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public int delete( Audio audio ) {
		return super.doDelete(audio);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public boolean exists( Integer idAudio ) {
		Object[] primaryKey = new Object[] { idAudio };
		return super.doExists(primaryKey);
	}
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public boolean exists( Audio audio ) {
		return super.doExists(audio);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	// Super class abstract methods implementation
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}
	//----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForInsert(Audio audio)  {
		return new Object[] {
			//--- Returns PRIMARY KEY and DATA ( for SQL "SET x=?, y=?, ..." )
			// "ID_AUDIO" is auto-incremented => no set in insert		
			audio.getNomAudio()  // "NOM_AUDIO" : java.lang.String
		};
	}
    //----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForUpdate(Audio audio) {
		return new Object[] {		
			//--- Returns DATA first ( for SQL "SET x=?, y=?, ..." )
			audio.getNomAudio(), // "NOM_AUDIO" : java.lang.String
			//--- Returns PRIMARY KEY at the end ( for SQL "WHERE key=?, ..." )
			audio.getIdAudio()  // "ID_AUDIO" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForPrimaryKey(Audio audio)  {
		return new Object[] {
			//--- Returns PRIMARY KEY values ( for SQL "WHERE key=?, ..." )
			audio.getIdAudio()  // "ID_AUDIO" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	@Override
	protected RowMapper<Audio> getRowMapper(Audio o)  {
		//--- RowMapper to populate the given bean instance
		return new AudioRowMapper(o) ;
	}
	//----------------------------------------------------------------------
	@Override
	protected RowMapper<Audio> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		return new AudioRowMapper( new Audio() ) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param audio
	 * @throws SQLException
	 */
	private void populateBean(ResultSet rs, Audio audio) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		audio.setIdAudio(rs.getInt("ID_AUDIO")); // java.lang.Integer
		if ( rs.wasNull() ) { audio.setIdAudio(null); }; // not primitive number => keep null value if any
		audio.setNomAudio(rs.getString("NOM_AUDIO")); // java.lang.String
	}

    //----------------------------------------------------------------------
	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	private class AudioRowMapper implements RowMapper<Audio> {

		/**
		 * The bean instance that will be populated from the ResultSet
		 */
		private final Audio bean ;
		
		/**
		 * Constructor
		 * @param bean the bean to be populated 
		 */
		AudioRowMapper(Audio bean) {
			this.bean = bean ;
		}
		
		@Override
		public Audio mapRow(ResultSet rs, int rowNum) throws SQLException {
			populateBean(rs, this.bean);
			return this.bean;
		}
	}
}
