/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.dao.impl.spring;

import java.sql.ResultSet;
import java.sql.SQLException;

import fr.formation.youtube.bean.Playlist;
import fr.formation.youtube.dao.PlaylistDAO;
import fr.formation.youtube.dao.impl.spring.commons.GenericDAO;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

/**
 * Playlist DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
@Repository
public class PlaylistDAOImplSpring extends GenericDAO<Playlist> implements PlaylistDAO {

	private final static String SQL_SELECT = 
		"select ID_PLAYLIST, FK_ID_UTILISATEUR, NOM_PLAYLIST from playlist where ID_PLAYLIST = ?";

	// NB : This entity has an auto-incremented primary key : "ID_PLAYLIST"
	private final static String AUTO_INCREMENTED_COLUMN = "ID_PLAYLIST";

	private final static int[] SQL_INSERT_TYPES = new int[] {
			java.sql.Types.INTEGER ,  // "FK_ID_UTILISATEUR" : INT UNSIGNED - java.lang.Integer
			java.sql.Types.VARCHAR   // "NOM_PLAYLIST" : VARCHAR(45) - java.lang.String
	};

	private final static String SQL_INSERT = 
		"insert into playlist ( FK_ID_UTILISATEUR, NOM_PLAYLIST ) values ( ?, ? )";

	private final static String SQL_UPDATE = 
		"update playlist set FK_ID_UTILISATEUR = ?, NOM_PLAYLIST = ? where ID_PLAYLIST = ?";

	private final static String SQL_DELETE = 
		"delete from playlist where ID_PLAYLIST = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from playlist";

	private final static String SQL_COUNT = 
		"select count(*) from playlist where ID_PLAYLIST = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public PlaylistDAOImplSpring() {
		super(AUTO_INCREMENTED_COLUMN, SQL_INSERT_TYPES);
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public Playlist find( Integer idPlaylist ) {
		Object[] primaryKey = new Object[] { idPlaylist };
		return super.doSelect(primaryKey);		
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public boolean load( Playlist playlist ) {
		return super.doSelect(playlist) ;
	}
	
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public Integer insert(Playlist playlist) {
		Long key = super.doInsertAutoIncr(playlist);
		return key.intValue();
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public int update(Playlist playlist) {
		return super.doUpdate(playlist);
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public int delete( Integer idPlaylist ) {
		Object[] primaryKey = new Object[] { idPlaylist };
		return super.doDelete(primaryKey);		
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public int delete( Playlist playlist ) {
		return super.doDelete(playlist);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public boolean exists( Integer idPlaylist ) {
		Object[] primaryKey = new Object[] { idPlaylist };
		return super.doExists(primaryKey);
	}
    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public boolean exists( Playlist playlist ) {
		return super.doExists(playlist);
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * DAO interface implementation
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	// Super class abstract methods implementation
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}
	//----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForInsert(Playlist playlist)  {
		return new Object[] {
			//--- Returns PRIMARY KEY and DATA ( for SQL "SET x=?, y=?, ..." )
			// "ID_PLAYLIST" is auto-incremented => no set in insert		
			playlist.getFkIdUtilisateur() , // "FK_ID_UTILISATEUR" : java.lang.Integer
			playlist.getNomPlaylist()  // "NOM_PLAYLIST" : java.lang.String
		};
	}
    //----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForUpdate(Playlist playlist) {
		return new Object[] {		
			//--- Returns DATA first ( for SQL "SET x=?, y=?, ..." )
			playlist.getFkIdUtilisateur(), // "FK_ID_UTILISATEUR" : java.lang.Integer
			playlist.getNomPlaylist(), // "NOM_PLAYLIST" : java.lang.String
			//--- Returns PRIMARY KEY at the end ( for SQL "WHERE key=?, ..." )
			playlist.getIdPlaylist()  // "ID_PLAYLIST" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	@Override
	protected Object[] getValuesForPrimaryKey(Playlist playlist)  {
		return new Object[] {
			//--- Returns PRIMARY KEY values ( for SQL "WHERE key=?, ..." )
			playlist.getIdPlaylist()  // "ID_PLAYLIST" : java.lang.Integer
		};
	}
	//----------------------------------------------------------------------
	@Override
	protected RowMapper<Playlist> getRowMapper(Playlist o)  {
		//--- RowMapper to populate the given bean instance
		return new PlaylistRowMapper(o) ;
	}
	//----------------------------------------------------------------------
	@Override
	protected RowMapper<Playlist> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		return new PlaylistRowMapper( new Playlist() ) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param playlist
	 * @throws SQLException
	 */
	private void populateBean(ResultSet rs, Playlist playlist) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		playlist.setIdPlaylist(rs.getInt("ID_PLAYLIST")); // java.lang.Integer
		if ( rs.wasNull() ) { playlist.setIdPlaylist(null); }; // not primitive number => keep null value if any
		playlist.setFkIdUtilisateur(rs.getInt("FK_ID_UTILISATEUR")); // java.lang.Integer
		if ( rs.wasNull() ) { playlist.setFkIdUtilisateur(null); }; // not primitive number => keep null value if any
		playlist.setNomPlaylist(rs.getString("NOM_PLAYLIST")); // java.lang.String
	}

    //----------------------------------------------------------------------
	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	private class PlaylistRowMapper implements RowMapper<Playlist> {

		/**
		 * The bean instance that will be populated from the ResultSet
		 */
		private final Playlist bean ;
		
		/**
		 * Constructor
		 * @param bean the bean to be populated 
		 */
		PlaylistRowMapper(Playlist bean) {
			this.bean = bean ;
		}
		
		@Override
		public Playlist mapRow(ResultSet rs, int rowNum) throws SQLException {
			populateBean(rs, this.bean);
			return this.bean;
		}
	}
}
