/*
 * Created on 17 Nov 2016 ( Time 21:47:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.formation.youtube.dao.commons;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;

/**
 * Utility class for JUnit test cases 
 * 
 * @author Telosys Tools
 *
 */
public class DAOTestUtil {
	
    /**
     * Creates a table that will be used by the DAO tests 
     * @param createTableSQL
     */
    public static void initDatabase(String createTableSQL) { 
    	//Message de début d'initialisation de création de table
    	System.out.println("===== initDatabase... ");
    	
    	// Injection de dépendence source JDBC properties
    	//--- The datasource as defined in the 'jdbc properties' file  
    	DataSource datasource = DAOProvider.getDataSource();
    	
    	// Exécution de requete SQL création de table
    	//--- Execute the CREATE TABLE SQL statement
    	try {
			createTable(createTableSQL, datasource);
		} catch (SQLException e) {
			e.printStackTrace();
			throw new RuntimeException("Error on 'create table'");
		}
    }
    // Méthode de connexion et d'execution  de la création de table précédente
    private static void createTable(String createTableSQL, DataSource datasource) throws SQLException {
    	Connection conn = datasource.getConnection();
    	Statement stmt = conn.createStatement();
    	int r = stmt.executeUpdate(createTableSQL);
    	System.out.println("create table status : " + r);
    	stmt.close();
    	conn.close();
    }
}
